apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.postgresql_name }}-files
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql_volume_size }}
  storageClassName: {{ .Values.storage_class_name }}
