apiVersion: v1
kind: Secret
metadata:
  annotations:
    template.openshift.io/expose-database-admin-password: '{.data[''database-admin-password'']}'
    template.openshift.io/expose-database-admin-user: '{.data[''database-admin-user'']}'
    template.openshift.io/expose-database-name: '{.data[''database-name'']}'
    template.openshift.io/expose-database-password: '{.data[''database-password'']}'
    template.openshift.io/expose-database-user: '{.data[''database-user'']}'
  name: {{ .Values.postgresql_name }}
stringData:
  database-admin-password: {{ .Values.postgresql_admin_password }}
  database-admin-user: postgres
  database-name: {{ .Values.postgresql_database_name }}
  database-password: {{ .Values.postgresql_password }}
  database-user: dbuser
