apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.omnidb_name }}-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.omnidb_volume_size }}
  storageClassName: {{ .Values.storage_class_name }}
